### PR TITLE
Handle payment_intent.failed event

### LINKED ISSUE #179: Handle `payment_intent.succeeded` webhook event
We'll get a `payment_intent.succeeded` webhook event whenever:

- A payment intent is captured from Stripe's dashboard
- A Solidus payment is manually captured from the admin interface (see #158)
- TODO: auto-capture is on, and an order is completed through a regular checkout (see #178)

We must update the Solidus counterpart for the first scenario by triggering the `complete` transition from the Solidus payments state machine. However, we need to be resilient because of the other two scenarios and the lack of guarantee that a webhook will only be received once and do nothing if the payment is already completed.

There's one caveat: Stripe allows to partially capture a payment, while Solidus doesn't. For that case, we'll update the `Spree::Payment#amount` field, and let's consider if we can add a log entry.

Partially replaces #160

### PR DESCRIPTION
**Pull request by waiting-for-dev**
## Summary

A `payment_intent.failed` event is [published](https://stripe.com/docs/payments/payment-intents/verifying-status#webhooks) when a payment intent can't be captured from Stripe.

After we check #185, the webhook could also be triggered by an action from the backend, so we need to do nothing if the payment is already failed.

Closes #179

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
👍

File: app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb [hunk 1]
```diff
@@ -27,6 +27,32 @@ def complete_payment(event)
...
+
+      # Voids a payment.
+      #
+      # Marks a Solidus payment associated to a Stripe payment intent as
+      # failed, adding a log entry about the event.
+      #
+      # @param event [SolidusStripe::Webhook::Event]
+      def fail_payment(event)
+        payment = extract_payment_from_event(event)
+        return if payment.failed?
```
Comment (loicginoux) [inline app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb:39]:
```suggestion
        return if !payment.can_failure?
```

I'd say that checking more generally if we can transition to failed is more generic and safe. You could be on a state (like checkout) where payment is not failed but doing the transition will raise an error. Same goes for the complete! event of the same file.

File: app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb [hunk 2]
```diff
@@ -27,6 +27,32 @@ def complete_payment(event)
...
+
+        payment.failure!.tap do
+          SolidusStripe::LogEntries.payment_log(
+            payment,
+            success: true,
```
Comment (elia) [inline app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb]: Shouldn't this be `false`?

Comment (waiting-for-dev) [reply app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb]: Oh, you're right. Changed! Thanks for pointing out.

I also added another commit to test the success value for both handlers in the subscriber class.

File: app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb (hunk 1 above)
Comment (waiting-for-dev) [reply app/subscribers/solidus_stripe/webhook/payment_intent_subscriber.rb:39]: Thanks for your suggestion, @loicginoux. If Solidus payment is in the `:checkout` state, but we're already getting a `payment_intent.payment_failed` webhook, that's probably an abnormal situation. I think it's better to be stricter so we can't detect any failure in our integration.
