### PR TITLE
Fix order cancel with Payment Intents captured payment

### LINKED ISSUE #56: [ADMIN] Order cancel doen't work with Payment Intents captured payments
When trying to cancel an order with an already captured payment made using the Payment Intents API, the application raises an error with the following message from Stripe:

```
A PaymentIntent object can be canceled when it is in one of these statuses: 
requires_payment_method, requires_capture, requires_confirmation, requires_action
```
This error can be avoided by refunding the payment (instead of canceling it) during the order canceling process.

### PR DESCRIPTION
**Pull request by spaghetticode**
Fixes https://github.com/solidusio/solidus_stripe/issues/56

This PR adds the `Spree::PaymentMethod::StripeCreditCard#try_void` method that is now called when an order is canceled in the admin area (Solidus used to call the now deprecated method `Spree::PaymentMethod#cancel`).

If we're dealing with a Payment Intents payment, and the payment is already captured, Stripe will not allow canceling it, we can only refund it. 

Also, a custom refund reason record is added via migration, in order to be able to clearly determine those payments that were refunded because there was no alternative.

### CODE REVIEW

File: app/models/spree/payment_method/stripe_credit_card.rb [hunk 1]
```diff
@@ -81,6 +83,19 @@ def void(response_code, _creditcard, _transaction_options)
         gateway.void(response_code, {})
       end
 
+      def try_void(payment)
+        if payment.completed?
+          reason = Spree::RefundReason.find_by(name: self.class::PAYMENT_INTENTS_REFUND_REASON) || Spree::RefundReason.first
```
Comment (ccarruitero) [inline app/models/spree/payment_method/stripe_credit_card.rb]: I think is just necessary `PAYMENTS_INTENTS_REFUND_REASON`, since the constant is in the same class.

Also, instead to fallback to first reason maybe we can use `find_or_create`?

Comment (spaghetticode) [reply app/models/spree/payment_method/stripe_credit_card.rb]: @ccarruitero thanks for spotting the issue with the constant, what was  I thinking when I wrote that?

I thought about using `find_or_create`, but then I went for the migration (the record is explicitly created in a more "expected" place) and the fallback to `Spree::RefundReason.first` for making the custom refund reason optional. 
But I think that your options are good as well. I'm wondering if a rake task for adding the refund reason might be a better option... does anybody want to share opinions on this?

Comment (kennyadsl) [reply app/models/spree/payment_method/stripe_credit_card.rb]: I have some concerns about creating a migration for this RefundReason. Can't we use an already existing one as default, like `Spree::Payment::Cancellation::DEFAULT_REASON`? Maybe also defined in a separate method so that people can customize it and use something else if needed?

File: app/models/spree/payment_method/stripe_credit_card.rb [hunk 2]
```diff
@@ -81,6 +81,22 @@ def void(response_code, _creditcard, _transaction_options)
...
 
+      def payment_intents_refund_reason
+        Spree::RefundReason.where(name: Spree::Payment::Cancellation::DEFAULT_REASON).first_or_create
+      end
+
+      def try_void(payment)
+        if v3_intents? && payment.completed?
+          Spree::Refund.create!(
+            payment: payment,
+            amount: payment.amount,
```
Comment (rainerdema) [inline app/models/spree/payment_method/stripe_credit_card.rb]: I think you can use [credit_allowed](https://github.com/solidusio/solidus/blob/475d9db5d0291dd4aeddc58ec919988c336729bb/core/app/models/spree/payment.rb#L143-L145) here (like in [Spree::Payment::Cancellation#cancel](https://github.com/solidusio/solidus/blob/b8296bdb5c9651e60239ab27c0093636981fd0aa/core/app/models/spree/payment/cancellation.rb#L34))
I don't think it's a problem for Stripe but, if there are some partial refunds already done, `credit_allowed` should give the correct amount to be refunded. WDYT?

File: app/models/spree/payment_method/stripe_credit_card.rb [hunk 3]
```diff
@@ -81,6 +81,21 @@ def void(response_code, _creditcard, _transaction_options)
         gateway.void(response_code, {})
       end
 
+      def payment_intents_refund_reason
+        Spree::RefundReason.where(name: Spree::Payment::Cancellation::DEFAULT_REASON).first_or_create
+      end
+
+      def try_void(payment)
+        if v3_intents? && payment.completed?
```
Comment (ChristianRimondi) [inline app/models/spree/payment_method/stripe_credit_card.rb:89]: Why don't you just return `false` here? It seems like solidus already handles the refund [here](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/payment/cancellation.rb#L30-L36) 🤔

Comment (spaghetticode) [reply app/models/spree/payment_method/stripe_credit_card.rb:89]: @ChristianRimondi that way the payment would remain to its original state, instead of becoming`void`, as this [line](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/payment/cancellation.rb#L32) would not run. That line executes [this method](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/payment/processing.rb#L190).

**Review by kennyadsl — APPROVED** [review]
