### PR TITLE
Fix `Gateway#purchase` not capturing the payment

### LINKED ISSUE #232: Change `Gateway#purchase` to both authorize and capture a payment
On Solidus, `Gateway#purchase` is meant to both authorize and capture a payment. However, we're only doing the first part, and the method actually contains what should be the `#authorize` method.

### PR DESCRIPTION
**Pull request by waiting-for-dev**
## Summary

On Solidus, `Gateway#purchase` is meant to authorize and capture a payment in a single step. However, we were using that method only to authorize (confirm, on Stripe) the payment.

We're now moving the authorize logic to a helper method shared by the `#authorize` and `#purchase` methods, while we use the `automatic` capture method on `#purchase`.

We're also unifying the format for the success messages recorded in the response.

We're getting rid of the option to pass custom payment intent options on `#authorize`. That was the only method in the gateway supporting them, and we can add it later to all the methods if we feel that's needed.

Closes #232

We take the occasion to perform some house-keeping (two last commits):

- Extract and reuse checks on the Gateway method arguments. We were only performing safety checks against `Gateway#capture` arguments. However, they also make sense for the other methods in the class. We're also adding unit tests for those checks.
- Unify naming convention for variables in the gateway tests

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

File: app/models/solidus_stripe/gateway.rb [hunk 1]
```diff
@@ -87,19 +91,20 @@ def capture(amount_in_cents, payment_intent_id, options = {})
...
-
+      stripe_payment_intent = create_stripe_payment_intent(
+        source,
+        options[:originator].order,
+        stripe_payment_intent_options: {
+          capture_method: "manual",
+          confirm: true
+        }
+      )
+      captured_stripe_payment_intent = capture_stripe_payment_intent(stripe_payment_intent.id)
```
Comment (elia) [inline app/models/solidus_stripe/gateway.rb]: It seems to me from the wording of the commit description that we're assuming that this method was not doing both authorization and capture before this change. 

Otherwise I'm not sure I understand why we're now doing the capture separately instead of at once with the default `capture_method`, which is _automatic_.

https://stripe.com/docs/api/payment_intents/create#create_payment_intent-capture_method

File: app/models/solidus_stripe/gateway.rb [hunk 2]
```diff
@@ -182,5 +176,26 @@ def create_stripe_payment_intent(source, order, stripe_payment_intent_options:)
     def capture_stripe_payment_intent(stripe_payment_intent_id)
       request { Stripe::PaymentIntent.capture(stripe_payment_intent_id) }
     end
+
+    def check_given_amount_matches_order_total(amount_in_cents, options)
```
Comment (elia) [inline app/models/solidus_stripe/gateway.rb]: There's no mention of the order here, thoughts on just stating that we _check given amount against the payment intent amount_?

**Review by elia — COMMENTED** [review]
Happy to see the gateway cleaned up 🙏 

Left a question plus a nit

File: app/models/solidus_stripe/gateway.rb [hunk 3]
```diff
@@ -51,28 +58,13 @@ def authorize(amount_in_cents, source, options = {})
...
+      check_payment_intent_id(payment_intent_id)
 
+      payment_intent = capture_stripe_payment_intent(payment_intent_id)
       build_payment_log(
         success: true,
-        message: "Capture was successful",
+        message: "PaymentIntent was confirmed successfully",
         response_code: payment_intent.id,
         data: payment_intent,
       )
```
Comment (rainerdema) [inline app/models/solidus_stripe/gateway.rb:70]: Not strictly related, but I was thinking about what happens in case of exceptions, and I noticed that we're logging a successful log with `build_payment_log(success: true, ...)`, but there might be cases where `capture_stripe_payment_intent` raises an error, and we handle only `Stripe::InvalidRequestError`.

Are we sure that this is the only exception to handle? I was looking for other possible exceptions, and maybe we can handle a more generic [`Stripe::StripeError`](https://github.com/stripe/stripe-ruby/blob/980b7b011f6fbff276ecadce5dd884e00669724f/lib/stripe/errors.rb#L6) at all the points when we're doing these external calls 🤔 WDYT?

If you believe this concern is not directly related to the changes proposed in this PR, we can discuss it at a later time 👍

File: app/models/solidus_stripe/gateway.rb (hunk 1 above)
Comment (waiting-for-dev) [reply app/models/solidus_stripe/gateway.rb]: I overlooked that! Thanks, I updated the code.

File: app/models/solidus_stripe/gateway.rb (hunk 2 above)
Comment (waiting-for-dev) [reply app/models/solidus_stripe/gateway.rb]: Makes sense. Changed!

**Review by rainerdema — APPROVED** [review]
Changes looks good, and I don't have much more to add. Great job! 👏

**Review by elia — APPROVED** [review]
🙌

**Comment by waiting-for-dev** [comment]
Rebasing on top of master after merging https://github.com/solidusio/solidus_stripe/pull/235 to fix CI

File: app/models/solidus_stripe/gateway.rb (hunk 3 above)
Comment (waiting-for-dev) [reply app/models/solidus_stripe/gateway.rb:70]: @rainerdema, yeah, it looks like, for now, only the happy path is covered in some situations, and I'm also unsure whether `InvalidRequestError` handles all possible failures. That's definitely food for another PR (probably related to #224)
