### PR TITLE
Fix error when completing an order with a card declined at confirmation

### LINKED ISSUE #224: Error when completing an order with a potential fraudulent payment
**Steps to reproduce**

- Perform a checkout and use [card number 4100000000000019](https://stripe.com/docs/testing#fraud-prevention) to pay with Stripe.
- The order advances successfully from the payment to the confirm step. However, when clicking on the "Complete" button (i.e., when Stripe tries to authorize the payment intent), a `Stripe::CardError` is raised.

[screencast-localhost_3000-2023.03.17-09_27_55.webm](https://user-images.githubusercontent.com/52650/225869555-47d6b55a-cc4f-454d-befa-04c68f7ab094.mp4)

### PR DESCRIPTION
**Pull request by waiting-for-dev**
## Summary

Stripe denies some payments at the confirmation stage, rather than in submitting the form. For those situations, we need to revert the order to the payment step and fail the payment.

Fixes #224

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by rainerdema — APPROVED** [review]
💯

File: app/models/solidus_stripe/gateway.rb [hunk 1]
```diff
@@ -48,7 +48,13 @@ def authorize(amount_in_cents, source, options = {})
         success: true,
         message: "PaymentIntent was confirmed successfully",
         response_code: stripe_payment_intent.id,
-        data: stripe_payment_intent,
+        data: stripe_payment_intent
```
Comment (elia) [inline app/models/solidus_stripe/gateway.rb:51]: super nit: leaving the final command will exclude the line from the diff, since it didn't actually change

**Review by elia — COMMENTED** [review]
✅

**Comment by elia** [comment]
_Sorry, I didn't mean to merge right away, hope it's fine tho, otherwise we can revert/reopen_

**Comment by waiting-for-dev** [comment]
> _Sorry, I didn't mean to merge right away, hope it's fine tho, otherwise we can revert/reopen_

No worries, it's only that I won't be able to address your super nit :smile:
